// AI Generated Notices Service
import PDFDocument from 'pdfkit'
import prisma from '../utils/prisma'

export interface NoticeData {
  type: 'WARNING' | 'CLOSURE' | 'COMPLIANCE' | 'SUMMARY'
  establishmentName: string
  establishmentAddress: string
  inspectionId: string
  violations: any[]
  inspectorName: string
  inspectionDate: Date
  deadline?: Date
  additionalNotes?: string
}

export class NoticeGeneratorService {
  // Generate Warning Notice
  async generateWarningNotice(data: NoticeData): Promise<string> {
    return this.generatePDFNotice(data, 'WARNING')
  }

  // Generate Closure Notice
  async generateClosureNotice(data: NoticeData): Promise<string> {
    return this.generatePDFNotice(data, 'CLOSURE')
  }

  // Generate Compliance Notice
  async generateComplianceNotice(data: NoticeData): Promise<string> {
    return this.generatePDFNotice(data, 'COMPLIANCE')
  }

  // Generate Inspection Summary Notice
  async generateSummaryNotice(data: NoticeData): Promise<string> {
    return this.generatePDFNotice(data, 'SUMMARY')
  }

  // Generate PDF Notice
  private async generatePDFNotice(data: NoticeData, noticeType: string): Promise<string> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument()
        const filename = `${noticeType.toLowerCase()}-${data.inspectionId}-${Date.now()}.pdf`
        const filepath = `uploads/notices/${filename}`

        const stream = require('fs').createWriteStream(filepath)
        doc.pipe(stream)

        // Header
        doc.fontSize(24).text('NIRIKSHA', { align: 'center' })
        doc.fontSize(14).text('Government Inspection Authority', { align: 'center' })
        doc.moveDown(2)

        // Notice Type
        doc.fontSize(20).text(`${noticeType} NOTICE`, { align: 'center', underline: true })
        doc.moveDown(2)

        // Notice Number and Date
        doc.fontSize(12).text(`Notice Number: NIR-${data.inspectionId.substring(0, 8).toUpperCase()}`)
        doc.text(`Date: ${new Date().toLocaleDateString()}`)
        doc.moveDown(2)

        // Establishment Details
        doc.fontSize(14).text('ESTABLISHMENT DETAILS', { underline: true })
        doc.moveDown()
        doc.fontSize(12).text(`Name: ${data.establishmentName}`)
        doc.text(`Address: ${data.establishmentAddress}`)
        doc.moveDown(2)

        // Inspection Details
        doc.fontSize(14).text('INSPECTION DETAILS', { underline: true })
        doc.moveDown()
        doc.fontSize(12).text(`Inspection ID: ${data.inspectionId}`)
        doc.text(`Inspection Date: ${data.inspectionDate.toLocaleDateString()}`)
        doc.text(`Inspector: ${data.inspectorName}`)
        doc.moveDown(2)

        // Content based on notice type
        this.addNoticeContent(doc, data, noticeType)

        // Footer
        doc.moveDown(3)
        doc.fontSize(10).text('This notice is generated by NIRIKSHA AI-powered inspection system.', { align: 'center' })
        doc.text('For queries, contact the Inspection Authority.', { align: 'center' })

        doc.end()

        stream.on('finish', () => {
          resolve(filepath)
        })

        stream.on('error', (error: any) => {
          reject(error)
        })
      } catch (error) {
        reject(error)
      }
    })
  }

  // Add content based on notice type
  private addNoticeContent(doc: PDFKit.PDFDocument, data: NoticeData, noticeType: string) {
    switch (noticeType) {
      case 'WARNING':
        this.addWarningContent(doc, data)
        break
      case 'CLOSURE':
        this.addClosureContent(doc, data)
        break
      case 'COMPLIANCE':
        this.addComplianceContent(doc, data)
        break
      case 'SUMMARY':
        this.addSummaryContent(doc, data)
        break
    }
  }

  private addWarningContent(doc: PDFKit.PDFDocument, data: NoticeData) {
    doc.fontSize(14).text('WARNING DETAILS', { underline: true })
    doc.moveDown()

    const criticalViolations = data.violations.filter((v: any) => v.severity === 'CRITICAL')
    const highViolations = data.violations.filter((v: any) => v.severity === 'HIGH')

    doc.fontSize(12).text(`This establishment has been issued a warning due to the following violations:`)
    doc.moveDown()

    if (criticalViolations.length > 0) {
      doc.text(`CRITICAL VIOLATIONS (${criticalViolations.length}):`, { underline: true })
      criticalViolations.forEach((v: any, index: number) => {
        doc.text(`${index + 1}. ${v.description}`)
      })
      doc.moveDown()
    }

    if (highViolations.length > 0) {
      doc.text(`HIGH SEVERITY VIOLATIONS (${highViolations.length}):`, { underline: true })
      highViolations.forEach((v: any, index: number) => {
        doc.text(`${index + 1}. ${v.description}`)
      })
      doc.moveDown()
    }

    doc.text('REQUIRED ACTIONS:', { underline: true })
    doc.text('- Immediate remediation of all critical violations')
    doc.text('- Submit remediation plan within 7 days')
    doc.text('- Schedule follow-up inspection')
    doc.moveDown()

    if (data.deadline) {
      doc.text(`Compliance Deadline: ${data.deadline.toLocaleDateString()}`)
    }

    if (data.additionalNotes) {
      doc.moveDown()
      doc.text('ADDITIONAL NOTES:', { underline: true })
      doc.text(data.additionalNotes)
    }
  }

  private addClosureContent(doc: PDFKit.PDFDocument, data: NoticeData) {
    doc.fontSize(14).text('CLOSURE ORDER', { underline: true })
    doc.moveDown()

    doc.fontSize(12).text(`NOTICE IS HEREBY GIVEN that ${data.establishmentName} is ordered to close operations immediately due to:`)
    doc.moveDown()

    const criticalViolations = data.violations.filter((v: any) => v.severity === 'CRITICAL')

    doc.text('CRITICAL VIOLATIONS REQUIRING IMMEDIATE CLOSURE:', { underline: true })
    criticalViolations.forEach((v: any, index: number) => {
      doc.text(`${index + 1}. ${v.description}`)
    })
    doc.moveDown()

    doc.text('CLOSURE CONDITIONS:', { underline: true })
    doc.text('- All operations must cease immediately')
    doc.text('- No public access permitted')
    doc.text('- All critical violations must be remediated')
    doc.text('- Reopening requires official inspection and approval')
    doc.moveDown()

    doc.text('REOPENING PROCESS:', { underline: true })
    doc.text('1. Submit remediation plan to Inspection Authority')
    doc.text('2. Schedule re-inspection with Authority')
    doc.text('3. Pass re-inspection with zero critical violations')
    doc.text('4. Obtain official reopening authorization')
    doc.moveDown()

    if (data.deadline) {
      doc.text(`Earliest Reopening Date: ${data.deadline.toLocaleDateString()}`)
    }

    doc.moveDown()
    doc.fontSize(10).fillColor('red').text('FAILURE TO COMPLY MAY RESULT IN LEGAL ACTION', { align: 'center' })
    doc.fillColor('black')
  }

  private addComplianceContent(doc: PDFKit.PDFDocument, data: NoticeData) {
    doc.fontSize(14).text('COMPLIANCE NOTICE', { underline: true })
    doc.moveDown()

    doc.fontSize(12).text(`This notice serves to inform ${data.establishmentName} of compliance requirements based on recent inspection.`)
    doc.moveDown()

    const compliantItems = data.violations.filter((v: any) => v.status === 'COMPLIANT')
    const nonCompliantItems = data.violations.filter((v: any) => v.status !== 'COMPLIANT')

    doc.text('COMPLIANCE STATUS:', { underline: true })
    doc.text(`Total Items Inspected: ${data.violations.length}`)
    doc.text(`Compliant Items: ${compliantItems.length}`)
    doc.text(`Non-Compliant Items: ${nonCompliantItems.length}`)
    doc.text(`Compliance Rate: ${((compliantItems.length / data.violations.length) * 100).toFixed(1)}%`)
    doc.moveDown()

    if (nonCompliantItems.length > 0) {
      doc.text('REQUIRED CORRECTIVE ACTIONS:', { underline: true })
      nonCompliantItems.forEach((v: any, index: number) => {
        doc.text(`${index + 1}. ${v.description} - ${v.severity} priority`)
      })
      doc.moveDown()
    }

    doc.text('COMPLIANCE REQUIREMENTS:', { underline: true })
    doc.text('- Address all non-compliant items within specified timeframe')
    doc.text('- Maintain documentation of corrective actions')
    doc.text('- Submit compliance report to Inspection Authority')
    doc.moveDown()

    if (data.deadline) {
      doc.text(`Compliance Deadline: ${data.deadline.toLocaleDateString()}`)
    }
  }

  private addSummaryContent(doc: PDFKit.PDFDocument, data: NoticeData) {
    doc.fontSize(14).text('INSPECTION SUMMARY', { underline: true })
    doc.moveDown()

    doc.fontSize(12).text(`Inspection of ${data.establishmentName} conducted on ${data.inspectionDate.toLocaleDateString()}`)
    doc.moveDown()

    const criticalViolations = data.violations.filter((v: any) => v.severity === 'CRITICAL')
    const highViolations = data.violations.filter((v: any) => v.severity === 'HIGH')
    const mediumViolations = data.violations.filter((v: any) => v.severity === 'MEDIUM')
    const lowViolations = data.violations.filter((v: any) => v.severity === 'LOW')

    doc.text('VIOLATION SUMMARY:', { underline: true })
    doc.text(`Critical: ${criticalViolations.length}`)
    doc.text(`High: ${highViolations.length}`)
    doc.text(`Medium: ${mediumViolations.length}`)
    doc.text(`Low: ${lowViolations.length}`)
    doc.text(`Total: ${data.violations.length}`)
    doc.moveDown()

    if (data.violations.length > 0) {
      doc.text('DETAILED FINDINGS:', { underline: true })
      data.violations.forEach((v: any, index: number) => {
        doc.text(`${index + 1}. [${v.severity}] ${v.description}`)
      })
      doc.moveDown()
    }

    doc.text('OVERALL ASSESSMENT:', { underline: true })
    if (criticalViolations.length > 0) {
      doc.text('FAIL - Critical violations require immediate action')
    } else if (highViolations.length > 2) {
      doc.text('CONDITIONAL PASS - Address high-priority violations')
    } else {
      doc.text('PASS - Establishment meets compliance standards')
    }
    doc.moveDown()

    if (data.additionalNotes) {
      doc.text('INSPECTOR NOTES:', { underline: true })
      doc.text(data.additionalNotes)
    }
  }

  // Generate notice from inspection ID
  async generateNoticeFromInspection(
    inspectionId: string,
    noticeType: 'WARNING' | 'CLOSURE' | 'COMPLIANCE' | 'SUMMARY'
  ): Promise<string> {
    const inspection = await prisma.inspection.findUnique({
      where: { id: inspectionId },
      include: {
        site: true,
        inspector: true,
        violations: true,
      },
    })

    if (!inspection) {
      throw new Error('Inspection not found')
    }

    const noticeData: NoticeData = {
      type: noticeType,
      establishmentName: inspection.site.name,
      establishmentAddress: inspection.site.address,
      inspectionId,
      violations: inspection.violations,
      inspectorName: inspection.inspector.name,
      inspectionDate: new Date(inspection.scheduledDate),
    }

    return this.generatePDFNotice(noticeData, noticeType)
  }

  // Get notice template
  getNoticeTemplate(noticeType: string): string {
    const templates = {
      WARNING: 'Warning Notice for establishments with critical or high-severity violations',
      CLOSURE: 'Closure Order for establishments with immediate health/safety risks',
      COMPLIANCE: 'Compliance Notice outlining required corrective actions',
      SUMMARY: 'Inspection Summary with overall assessment and findings',
    }

    return templates[noticeType as keyof typeof templates] || 'Unknown notice type'
  }
}

export const noticeGenerator = new NoticeGeneratorService()
